version: "3.8"

services:
  blogdb:
    container_name: blogdb
    image: mysql
    ports:
      - "${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQLDB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQLDB_DATABASE}"

  spring-boot-blog:
    container_name: spring-boot-blog
    image: xiyuantu/spring-boot-blog
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    depends_on:
      - blogdb
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://blogdb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}"
      SPRING_DATASOURCE_USERNAME: "${MYSQLDB_USER}"
      SPRING_DATASOURCE_PASSWORD: "${MYSQLDB_ROOT_PASSWORD}"
    restart: on-failure