spring:
  datasource:
    url: jdbc:mysql://localhost:33066/blog
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080

jwt:
  secret: 98ebaab7130a31f8d208d97b6c46c036279d994229f4b9e612f2e901b2421feb
  expiration-milliseconds: 604800000
